require('..').setup(); //(activate stubs for subsequent requires)

const { execFileSync } = require('child_process'); //(utility to run child scripts)
const path = require('path'); //(resolve helper script path)

function runWithoutSetup(){ //(spawn child process without setup)
 console.log(`runWithoutSetup is running with none`); //(start log)
 try{ //(attempt to execute)
  const script = path.join(__dirname, 'withoutSetup.js'); //(child script path)
  const out = execFileSync(process.execPath, [script], { env: { NODE_PATH: '' } }).toString(); //(run child with clean env)
  const res = JSON.parse(out); //(parse returned JSON)
  console.log(`runWithoutSetup is returning ${JSON.stringify(res)}`); //(return log)
  return res; //(forward result)
 }catch(error){ //(handle errors)
  console.error(error); //(output problem)
  return {}; //(fallback result)
 }
} //(end runWithoutSetup)

function runWithSetup(){ //(spawn child process with setup required)
 console.log(`runWithSetup is running with none`); //(start log)
 try{ //(attempt execution)
  const script = path.join(__dirname, 'withoutSetup.js'); //(child script path)
  const setupPath = path.join(__dirname, '../setup'); //(setup file path)
  const out = execFileSync(process.execPath, ['-r', setupPath, script], { env: { NODE_PATH: '' } }).toString(); //(run child with setup)
  const res = JSON.parse(out); //(parse returned JSON)
  console.log(`runWithSetup is returning ${JSON.stringify(res)}`); //(return log)
  return res; //(forward result)
 }catch(error){ //(handle errors)
  console.error(error); //(output problem)
  return {}; //(fallback result)
 }
} //(end runWithSetup)

test('child process uses stubs when setup is required', () => { //(jest test case)
 console.log(`setupResolutionTest is running with none`); //(start log)
 const withSetup = runWithSetup(); //(result when setup loaded)
 const withoutSetup = runWithoutSetup(); //(result when setup absent)
 expect(withSetup.axiosStub).toBe(true); //(axios should be stubbed)
 expect(withSetup.winstonStub).toBe(true); //(winston should be stubbed)
 expect(withoutSetup.axiosStub).toBe(false); //(axios should be real)
 expect(withoutSetup.winstonStub).toBe(false); //(winston should be real)
 console.log(`setupResolutionTest has run resulting in pass`); //(end log)
});
