// GENERATED RUNNER: qtests-runner.mjs — Node ESM runner that invokes Jest with stable config
// This file is auto-generated by qtests. Safe to delete; generator will recreate.
import { spawn } from 'child_process';
import path from 'path';

const args = process.argv.slice(2);
const jestArgs = [
  '--config',
  path.join(process.cwd(), 'config', 'jest.config.mjs'),
  '--passWithNoTests',
  ...args,
];

const child = spawn('jest', jestArgs, { stdio: 'inherit', shell: true });
child.on('exit', (code) => process.exit(code || 0));