const express=require('express');const helmet=require('helmet');const cors=require('cors');const winston=require('winston');const qerrors=require('qerrors');
const logger=winston.createLogger({level:'info',transports:[new winston.transports.Console({silent:false})]});
const app=express();
app.use(helmet({contentSecurityPolicy:process.env.NODE_ENV==='production'?{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],imgSrc:["'self'","data:","https:"],}}:false,hsts:process.env.NODE_ENV==='production'?{maxAge:31536000,includeSubDomains:true,preload:true}:false}));
app.use(cors({origin:process.env.NODE_ENV==='production'?(process.env.ALLOWED_ORIGINS?process.env.ALLOWED_ORIGINS.split(','):['https://yourdomain.com']):true,credentials:true,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));
app.use(express.json({verify:(req,res,buf)=>{try{JSON.parse(buf.toString());}catch(error){qerrors(error,'express.json: parsing request body',{url:req.url,method:req.method});throw error;}}}));
app.use((req,_res,next)=>{try{logger.info(`REQ ${req.method} ${req.url}`);}catch(e){}next();});
const helloRouter=require('./routes/hello');const calculatorRouter=require('./routes/calculator');const statusRouter=require('./routes/status');const rootRouter=require('./routes/root');const usersRouter=require('./routes/users');
app.use('/api',helloRouter);app.use('/api',calculatorRouter);app.use('/api',statusRouter);app.use('/api',usersRouter);app.use('/',rootRouter);
app.get('/health',(_req,res)=>res.status(200).json({ok:true}));
app.get('/api/health',(_req,res)=>res.status(200).json({ok:true,status:'healthy',timestamp:new Date().toISOString()}));
app.use((error,req,res,next)=>{qerrors(error,'express.global: unhandled error',{url:req.url,method:req.method});res.status(500).json({error:'Internal server error'});});
module.exports=app;