/** Email Sender Core Utility - TypeScript Implementation */
import{logStart,logReturn}from'../../lib/logUtils.js';import{validateEmail}from'./emailValidator.js';import{formatEmailContent}from'./emailFormatter.js';import{addToHistory,type EmailHistoryEntry}from'./emailHistory.js';import{randomBytes}from'crypto';import{validateArray}from'../helpers/validation.js';import{createTimestamp}from'../helpers/timeUtils.js';import{truncateString}from'../helpers/stringUtils.js';
interface EmailOptions{verbose?:boolean;[key:string]:any;}
interface EmailResponse{success:boolean;emailData?:any;message:string;timestamp:Date;id?:string;error?:string;}
interface EmailBatchItem{to?:string;recipient?:string;subject:string;body:string;options?:EmailOptions;}
interface BatchResult{success:boolean;message?:string;results:EmailResponse[];summary:{total:number;successful:number;failed:number;};}

const sendEmail=(recipient:string,subject:string,body:string,options:EmailOptions={}):EmailResponse=>{logStart('sendEmail',recipient,subject,body,options);if(!validateEmail(recipient)){const error:EmailResponse={success:false,emailData:null,message:`Invalid email address: ${recipient}`,timestamp:new Date(),error:'INVALID_RECIPIENT'};addToHistory(error);console.log(`[MOCK EMAIL ERROR] Invalid recipient: ${recipient}`);logReturn('sendEmail',error);return error;}const formatted=formatEmailContent(subject,body);const emailData={to:recipient,subject:formatted.subject,body:formatted.body,...options};const response:EmailResponse={success:true,emailData,message:"Client should send this email using preferred mail service",timestamp:new Date(),id:`mock-email-${Date.now()}-${randomBytes(4).toString('hex')}`};addToHistory(response);console.log(`[MOCK EMAIL] To: ${recipient}, Subject: ${formatted.subject}`);options.verbose&&console.log(`[MOCK EMAIL] Body: ${truncateString(formatted.body,100)}`);logReturn('sendEmail',response);return response;};

const sendEmailBatch=(emails:EmailBatchItem[],options:EmailOptions={}):BatchResult=>{logStart('sendEmailBatch',emails,options);try{validateArray(emails,'emails');}catch(error){const errorResult:BatchResult={success:false,message:'sendEmailBatch requires an array of email objects',results:[],summary:{total:0,successful:0,failed:1}};logReturn('sendEmailBatch',errorResult);return errorResult;}const results:EmailResponse[]=[];let successful=0,failed=0;for(const email of emails){try{const result=sendEmail(email.to||email.recipient||'',email.subject,email.body,{...options,...email.options});results.push(result);result.success?successful++:failed++;}catch(error:any){const errorResult:EmailResponse={success:false,emailData:null,message:`Failed to process email: ${error.message}`,timestamp:createTimestamp(),error:'PROCESSING_ERROR'};results.push(errorResult);failed++;}}const batchResult:BatchResult={success:failed===0,results,summary:{total:emails.length,successful,failed}};batchResult.message=failed>0?`Batch completed with ${failed} failures out of ${emails.length} emails`:`Batch completed successfully - ${successful} emails processed`;logReturn('sendEmailBatch',batchResult);return batchResult;};
export { sendEmail, sendEmailBatch, validateEmail, formatEmailContent, addToHistory };
export type { EmailOptions, EmailResponse, EmailBatchItem, BatchResult };

// Legacy type exports for backward compatibility  
export type { EmailHistoryEntry as EmailData, EmailHistoryEntry as LegacyEmailResult } from './emailHistory.js';