// config/jest-setup.ts - generated by qtests
// IMPORTANT: Always load qtests setup FIRST so module stubs are in place before user imports.
import 'qtests/setup';
import stubs from 'qtests/lib/stubs.js';
import { jest as jestFromGlobals } from '@jest/globals';

const J = (globalThis && globalThis.jest) ? globalThis.jest : jestFromGlobals;
if (!globalThis.jest && J) {
  globalThis.jest = J;
}

// Jest does not use Node's Module._load for test module resolution, so we must register Jest mocks explicitly.
const j = globalThis.jest || J;
if (j && typeof j.mock === 'function') {
  const axiosStub = (stubs && stubs.axios) ? stubs.axios : {};
  const winstonStub = (stubs && stubs.winston) ? stubs.winston : {};
  j.mock('axios', () => axiosStub);
  j.mock('winston', () => winstonStub);
}

beforeAll(() => {
  const j = globalThis.jest || J;
  if (j && typeof j.setTimeout === 'function') j.setTimeout(10000);
});

afterEach(() => {
  const j = globalThis.jest || J;
  if (j && typeof j.clearAllMocks === 'function') j.clearAllMocks();
});
